//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intention
    {
        public int intentionId { get; set; }
        public string userId { get; set; }
        public string offeredBy { get; set; }
        public Nullable<int> intentionType { get; set; }
        public Nullable<System.DateTime> intentionDate { get; set; }
        public string massTime { get; set; }
        public string intentionDetails { get; set; }
        public Nullable<int> intentionStatus { get; set; }
    
        public virtual IntentionCategory IntentionCategory { get; set; }
    }
}
