//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntentionDetail
    {
        public int id { get; set; }
        public Nullable<int> intentionId { get; set; }
        public Nullable<int> paymentId { get; set; }
    
        public virtual IntentionDetail IntentionDetail1 { get; set; }
        public virtual IntentionDetail IntentionDetail2 { get; set; }
    }
}
